### ISSUE TITLE
[Bug] VSCode Typescript language server crashes

### ISSUE THREAD

**Issue by StefanoMagrassi** [apache/echarts#16198]
### Version

5.2.2

### Link to Minimal Reproduction

https://github.com/yanstars/vscode-bug-report

### Steps to Reproduce

1. install `echarts` v5.2.2 or above
2. upgrade vscode to v1.63.0 or use Typescript v4.5.0 (or above) as workspace ts version;
3. run vscode

### Current Behavior

The editor reports this error:

> The TypeScript language service died 5 times right after it got started. The service will not be restarted

### Expected Behavior

The TypeScript language server should not crash...

### Environment

```markdown
- OS: Ubuntu 20.04
- Browser: any
- Framework: any
```

### Any additional comments?

Related issue in VSCode repository -> microsoft/vscode#138334

**Comment by Bearprimer** [comment]
The vscode 1.63.2 is appears to fix this bug

**Comment by plainheart** [comment]
Thank you all. I'm going to close it as it was fixed in the latest VS Code.

**Comment by dmateusp** [comment]
FYI I was still hitting the same issue in VSCode `1.63.2`, so I tried to compile directly with `tsc` instead

With typescript `4.5` I hit the same issue, but with typescript `4.4` it works..

```bash
❯ tsc -v
Version 4.5.3
❯ tsc
/usr/local/lib/node_modules/typescript/lib/tsc.js:47148
            if (type.flags & 524288) {
                     ^

TypeError: Cannot read properties of undefined (reading 'flags')
    at getPropertyOfObjectType (/usr/local/lib/node_modules/typescript/lib/tsc.js:47148:22)
    at getPropertyOfType (/usr/local/lib/node_modules/typescript/lib/tsc.js:47710:24)
    at resolveESModuleSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:40904:54)
    at getTargetOfNamespaceImport (/usr/local/lib/node_modules/typescript/lib/tsc.js:40191:28)
    at getTargetOfAliasDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:40405:28)
    at resolveAlias (/usr/local/lib/node_modules/typescript/lib/tsc.js:40446:30)
    at getSymbol (/usr/local/lib/node_modules/typescript/lib/tsc.js:39225:38)
    at resolveNameHelper (/usr/local/lib/node_modules/typescript/lib/tsc.js:39464:34)
    at resolveName (/usr/local/lib/node_modules/typescript/lib/tsc.js:39448:20)
    at resolveEntityName (/usr/local/lib/node_modules/typescript/lib/tsc.js:40573:42)

Node.js v17.0.1

```

```bash
❯ npm install --global typescript@~4.4.0

changed 1 package, and audited 2 packages in 995ms

found 0 vulnerabilities
❯ tsc -v
Version 4.4.4
❯ tsc
[EDITED: returns expected compile issues I was having in my project instead of the "flags" error]
```
