### ISSUE TITLE
[Bug] Setting the wrong configuration after re-setting the correct invalid （设置错误的配置后重新设置正确的无效）

### ISSUE THREAD

**Issue by hai2007** [apache/echarts#16608]
### Version

5.2.2

### Steps to Reproduce

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <script src="./echarts-5.2.2.js"></script>
</head>

<body>

    <div style="width:400px;height:400px"></div>

    <script>
        var handler = echarts.init(document.getElementsByTagName('div')[0]);

      try{
        handler.setOption({
            "xAxis": {
                "type": "category",
                "data": [
                "一","二","三","四","五","六","七"
                ]
            },
            "yAxis": {
                "type": "value"
            },
            "series": [
                {
                    "data": {},
                    "type": "bar"
                }
            ]
        })
      }catch(e){
          console.error(e);
      }

      setTimeout(function(){
        // handler.clear();
        handler.setOption({
            "xAxis": {
                "type": "category",
                "data": [
                    "一","二","三","四","五","六","七"
                ]
            },
            "yAxis": {
                "type": "value"
            },
            "series": [
                {
                    "data": [
                        "4","9","2","8","8","6","4"
                    ],
                    "type": "bar"
                }
            ]
        });
      },1000)
    </script>

</body>

</html>
```

### Current Behavior

```js

echarts.js:566 Uncaught Error: `setOption` should not be called during main process.
    at assert (echarts.js:566:19)
    at ECharts.setOption (echarts.js:29721:11)
    at ECharts.clear (echarts.js:30187:14)
    at index.html:39:17
```

### Expected Behavior

正确绘制

### Environment

```markdown
- OS:win11
- Browser:Chrome/98.0.4758.102
- Framework:无
```

**Comment by plainheart** [comment]
Please try to upgrade to v5.3.0 and check if this issue persists. It was improved in #16395.
