### ISSUE TITLE
[Bug] echarts-gl的3D曲面图在大数据量时出错，显示空白

### ISSUE THREAD

**Issue by schzh** [apache/echarts#16763]
### Version

2.0.9

### Steps to Reproduce

在数据量达到一个数量级时，例如x坐标是1天的0-1440分钟，y坐标是1-2000，1440*2000大约不到300万数据点，这时候3D曲面图出错，绘图区显示一片空白，但是鼠标滑过绘图区仍然有tooltips。印象里50万数据量以下没问题。

### Current Behavior

3D曲面图在50万数量级以上出错，一片空白。

### Expected Behavior

可以显示较大的数据量，或者给出比较明确的数据量的上限值是多少

### Environment

```markdown
- OS:WIN 10
- Browser:Chrome最新
- Framework:
```

### Any additional comments?

echarts-gl.min.js:1 Uncaught Error: 
1: #define DIRECTIONAL_LIGHT_COUNT 1
2: #define AMBIENT_LIGHT_COUNT 1
3: #define TEXTUREATLAS_ENABLED
4: attribute vec3 position;
5: 
6: attribute vec2 texcoord;
7: 
8: attribute vec2 offset;
9: 
10: #ifdef VERTEX_COLOR
11: attribute vec4 a_Color;
12: 
13: varying vec4 v_Color;
14: #endif
15: 
16: uniform mat4 worldViewProjection;
17: 
18: uniform vec4 viewport;
19: 
20: 
21: varying vec2 v_Texcoord;
22: 
23: void main()
24: {
25:  vec4 proj = worldViewProjection * vec4(position, 1.0);
26: 
27:  vec2 screen = (proj.xy / abs(proj.w) + 1.0) * 0.5 * viewport.zw;
28: 
29:  screen += offset;
30: 
31:  proj.xy = (screen / viewport.zw - 0.5) * 2.0 * abs(proj.w);
32:  gl_Position = proj;
33: #ifdef VERTEX_COLOR
34:  v_Color = a_Color;
35: #endif
36:  v_Texcoord = texcoord;
37: }
38: 
    at l.validateProgram (echarts-gl.min.js:1:58342)
    at l.updatePrograms (echarts-gl.min.js:1:58726)
    at l.renderPass (echarts-gl.min.js:1:59038)
    at l.render (echarts-gl.min.js:1:57911)
    at Ol._doRender (echarts-gl.min.js:1:427571)
    at Ol.render (echarts-gl.min.js:1:425929)
    at Ja._doRender (echarts-gl.min.js:1:254024)
    at Ja.refresh (echarts-gl.min.js:1:253593)
    at t.refresh (echarts.min.js:16:12838)
    at t.refreshImmediately (echarts.min.js:11:3427)
validateProgram @ echarts-gl.min.js:1
updatePrograms @ echarts-gl.min.js:1
renderPass @ echarts-gl.min.js:1
render @ echarts-gl.min.js:1
Ol._doRender @ echarts-gl.min.js:1
Ol.render @ echarts-gl.min.js:1
Ja._doRender @ echarts-gl.min.js:1
Ja.refresh @ echarts-gl.min.js:1
t.refresh @ echarts.min.js:16
t.refreshImmediately @ echarts.min.js:11
t._flush @ echarts.min.js:11
animation.rT.stage.update @ echarts.min.js:11
n.update @ echarts.min.js:10
t @ echarts.min.js:10
arj40.htm:1 [.WebGL-02936E00] GL_OUT_OF_MEMORY: Internal D3D9 error: HRESULT: 0x8876017C: Failed to allocate internal vertex buffer
8[.WebGL-02936E00] GL_CONTEXT_LOST_KHR: Context has been lost.

**Comment by schzh** [comment]
目前是我自己对数据做了预处理，如果超出50万，那么做了分段平均（或者分段最大值、分段界值，根据实际需要）。不过如果GL确实无法兼容大数据量，还是想知道确切的数据量上限是多少(50万是我估计的)，好做出针对性的处理。沈先生能告知数据量上限吗 @pissang
