### ISSUE TITLE
[Bug] Using Line chart type,legend throw error out.

### ISSUE THREAD

**Issue by lszgit241** [apache/echarts#17926]
### Version

5.4.0

### Link to Minimal Reproduction

[Reproduction Link](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurGKIQIwBsANMejhgBZiVUAMdJsARsGGQC2hAEwAWLiQA2AUwBmrWB2IBfSbIwzoBItwDOTYAHdCYLAFcZk9MBxbFAcgBuMrJADGAQykPrpAJ4gMoQOeu5YwFI-fp7QEIKekDAAIuZYiVDQAKoguInBsNSc9LCMLITF-jKy7mAyOqjc6A6AfHKApUaAi26A5cYUgP1-DqYWViXN7d0i_YRy3nrDTbCtnV0AzJOw01KzfqNLYmsbWyMLY10ArPszc02L3VQXm1fcN10A7PeH888AHO-PJM99AC0gFklQAAcoBT0wGpCG22OSwmIIhULMllhz1WiMhg1RR2ee0xyJhuJO5wJ2L-O1uvTJ0JxnxObxpKIpcO6PyZRPpSwogMAIRmAM2jCXTricRHzBeS0SdluKhSy8bLJcSlqdFbT5ScqGrmVKli9tZyRUsvgbLCU1CU8mBPIQANpHRrzWDQTyCAoA_pHC3zR3zF1ukKiz3zb1NX1Nf3u6XBpqh7jh7iRwO7GPcOMkBMkJOss6pkjp9CZ9DZ553Bxe2FF52uqN6vPoAu6J0lk4_cshkoAXVUkgAHgBBXsQPR2kqZsCBd2QN2-I6eId6AAynh41UIVfckVsIQAxKcAGIcKjLWdO9YwMAAZQgAC8ChQRBW5wuACoQdwAa3XR3QBmMU0uJ95nnYdFwgaACirKRwJkS8J1kb8z3QTcpG3BYdwAYS-DCAE4MIw9snRUL1zWITtJH8Qdh1HeNn1Alc1ybeYULQhw90Pdhj1PJ05Ava870oR8Q1hPQQGgsAwIgxCnWgiC4P8BCmKdCcghCPIDHqQiO2Eo4VPdJxvEsLTYGI9ByOIWY7BHWB7Vo-YBwXABJbQZF7CpYUopyXLc2BKiaPSQlkmRuP0QRgH4JglXmP8jEvfxBD4KQAIeWEW25fpYQgOpBHkxSNy3LBd2WMQcIofd-2MhtYStG0bJ_GzqDEKgKFOdgxHYDqOpoWAxGWU4cK-cyz1tRrmtOdrOq62Avk405TiGp0RqoJqWpeDhJu6sQRGWDqFvmJaVuakRJs4WAXjEF4vmWPamgO5rlpmjaeq-L4cJeG7uDu6gvgmzruooZYvla7t5hB_M_EzBzh2c3BXPco5POh7z4fmAKFiCkKSD0MKIqipoYrihLImSj4IxrZNxgyo4spkHL4Mg-qWMK9CKDEXDcMqkzqsSWrbMW0aWrak7utOHacKoD6SC-8aTtOr5tuOyX0GltbhcKZYcP6pWGuW-6HzVlr5ZEbWvoetWRFK16TYFqgfrVtbtolo4waqscjihvQYbh3yPKoz3kZ93TJ0CmDMd_HGwEi9URMMWL4sSkmWTS7pVjD2AabphSGbPJndw6gAhLaKqApoapo_ndcF36ppeY6cLEa3K5ltWvioObrthZWBdOVWno4EQgcbw79aekrlvmzudcOsRHr-nra_YDv6tNu2npEF4xZdkgt_TSG_a9ny_O4RH_dhw_YTRhwMZEiOo51I4Cfj4n1kuVLyZzPY04z3Ls6dXP0JwvuZI-cKDJE5o2MudVhrdyFk9YqpUl7QKbtXKamtThXSHmNXuc9jw7UwdQEec8XjsAnsvG2M8DYtWKvg22KD_o4WWKzLeZlzQQ3dvvAOR8SAnwPijfywd0ahxvuFSOeN9Cx0JgnF-KUjjJ1zF_bKP9pLMQKrucqyQMIUBwuA7m1py77RgXQpQHUqAS0ntLFBp1liXQbuY7u2CppfBeD3RBFdh7HSevXC2g07GVzNqPVu50aGrznqcAGl1mGwB3mw-yHCz58OPnE72XD0CX2vg_W-YisYSKfklaRpNEzv1LFTeY396bKKaP_Ni-59wvGSB1HRRxIF8wMU3WBc9ljbVFvg5uT0XgUHlqQpBK0e7rRwewAetiyF-MIVNZY1j-k0IoZ448A9glGNbtYp2oNWFu1iV5eJgd5g8M4RfARV8hEZJEXfQ04jjCSOfgcJORSGQlKaGUrOFTuBVJ3PuUW-5lj7kafMZp0yRntKmqcDg4semWM2vXFqPSHGnQoJdRFvj3Fqw4GEpZs85ni0WRi-6ISpqmPYBQdgkTol7KaB7XhRymgnMOSkgIqlBEQTTtja5WTfw5KJnkp5b8Aw5jbJlRR5SlLfNUehWuIgACiyQKDAtLjzfRt1DH2yoBbVxrSRlwtgOvGeQy3FYLGY4gZYhjW6r1h4ohmszFgvussuercBpTOGcSoxqL2o4SpbsuytKknnwRkGhJJA0mXOipk6OD8-VSMFUcIKSjJXhvOepJgmkS6FOFR6AkYrabJvyqhZmbF4FlWLjpEFqqoEmqri3EQVAIlEpavqoGTjjbNtGfbeWJUaGzLlu1deuKW52x1eqvxJLTpbVag3Z2_qMzsIOck32S7g2o3OekqN3KY3RTjY81-iaYKFvqpfdNmbK1kxzUGPN1NxWfJTchaVbFWbs20VmkgoKPV1qejNfqvrO36v6egigSKzWnW2vM_9jqCG2qmuII6w6-liAfO62ttD7Y4Ter6udaYYmBtXWG9ATLl1BzZRcjlwjcY7vxnugVB75hJolVWU9ngNK4GVdm2sKdqRgkhPmzOeVGZPp3AXIuHGP3VpaeO8FRi26tR8dB3pRCBnWNA2rfqPdUPWpgwbV66LoP-Lngwzp6y1Y4WOhwP1uGaXcDpackNBGGXcAjRRq5VH767vubkxOsJGP3uY2m1jGb2PvuLC8lMN7Sl3sEznYTgDgGgPE-gT9taZ31pEFC2FsturmeoB2xTyL_pFD7bB06Y1kOIZwZ0zDpmf1QsGjh8GNmSB2eZSupGbXSPuk3fjaNHmaNef5T5w9ckmMnsC2xpL1Yr0qh40ifjx7YvFrUf2DRWipspe02lvuA93oAeyz1DLPc1N90Fgpr9R1zbkpEPli7zq5k3bWrVl1r1gaNddgG2zoanPcO-yylzwVKOiOo3cuOQ38ksj8zF5SE3gtTbkXcSL7zou_xUct9CNS6kNNC7ATb0mxoQrlsDfbasdpopO0Q5q520P9s2l8ClY7PrkLxWV9gpVKXNvQ30q68srNNc-y1v77XT4kfXWRnroVt39dBw8ujMiGNHrG2eFjk2cdyMZLxhRBald_2E38wFgKNuScU4T7qy1xZQa_UpxxbOcIc4K2B7qIgW0lbVk1cle2DP3dOi8TWvbOeTu6u2rW72ubNfQK10XjKhddZDq5rd7nbnZMG_G-jTQoeo_4WRs9IWL2cYpl0dkmuFs67R6xHcsqFVKpx3jpnbSjEW3q1lrFpUKAgc7YVw7bP7cXdpz1ClvVKuQtZhdZ7cHlpBND7vRdHWo-JMc_9jdkbetS6T7ylP-75eXq4z0WUJf_NCfR9U_ck0jd6JrVt03hRLX-8U_qzpCyKdzMNp73vpWcuPUt2h733VnEvUZ1LDbIHgan1K3Hzh9guvsrPmutHgvmcuLsvpLonsKDLt5hDkKjvmKAKFrgJpnlKkfr8ifp1GfrzCbrJhSkEiTj-iVOSk_j7lQKVF_tppdk9G3uvFavjo1Czjlugt0gHl6sVEOlPnhl9nAQ5tAYRqyt1ogVjH1mvrAI_ODgmn6OFinHvretrgfktuXjUqfjXsblblfp0i9LdqloBj9AMnQWbg-JQQZn3lonNKYcwT_rAIwr7lppwVznPFtBvNsk0NSgLhHjHscsEVntIfHivsgSyIoanlvvnh_OoVFpodDmXiWoQXoXnhJuflJnXjJvbGzlos3n0j3D3qlp3hbAwu3nYe_q4XJq_t_twa4TtE4Z4cAbbMsAweAWHoEbAJHjAfPhIT9qkkvhEUgcDtLsnmDrEQUlmKoWcIkcjskXgSQD8rocQfodkWQebK9M7kUZTvalYU0YEq7j-jdhgpzi4aiqzC0bkZ6i3BrE1F0dPlASLv0b9mIWLuEYDm5uMfITEZvjMWFjNrcAsdwB8ikZUnrkQdjpkclgYallfm3log6lbq2uNC8PUVtp3tQLXB4bcTpnAg2rsRcY0VdONGPqdOLKivNMIeHr0aEQMa8ZIQDpynISgZMbLsNiocCa8KCSQOCcsY-gQWsTCbGLoqQYYUYhdAQnsTXGIJakwZwV2mvGihwfiSwR0uSp0SSfbOvIvBSf9JattE8SIYLh8bAYMYvggaMbIavuyevlMQCc8jySaNgfvhCfgTodCewCQWqvidtnPNQJrKUVtoBi4lUVbp3uNFdHiYATMjUQ9LfndqSc0TcXGYdMAQDEDLOjsmmGRCgCoAANxAA)

### Steps to Reproduce

version 5.4.0

### Current Behavior

echarts.js:1591 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at LineView2.render (LineView.js:567:36)
    at Task2.progress (Chart.js:233:20)
    at Task2._doProgress (task.js:187:10)
    at Task2.perform (task.js:153:16)
    at echarts.js:1825:24
    at GlobalModel2.<anonymous> (Global.js:654:10)
    at Array.forEach (<anonymous>)
    at each (util.js:205:13)
    at GlobalModel2.eachSeries (Global.js:651:5)
    at renderSeries (echarts.js:1813:15)

### Expected Behavior

I can't do anything in legend except scroll buttons 

### Environment

```markdown
- OS:mac
- Browser:chrome
- Framework:none
```

### Any additional comments?

```js
option = {
    "grid": {
        "top": 16,
        "right": 160,
        "bottom": 24,
        "left": 60
    },
    "legend": {
        "show": true,
        "orient": "vertical",
        "type": "scroll",
        "animationDurationUpdate": 160,
        "right": 0,
        "selected": {
            "举报监控1线": true,
            "举报监控2线": false,
            "举报监控3线": false,
            "举报监控4线": false,
            "举报监控5线": false,
            "举报监控6线": false,
            "举报监控7线": false,
            "举报监控8线": false,
            "举报监控1线-前一日": true,
            "举报监控2线-前一日": true,
            "举报监控3线-前一日": true,
            "举报监控4线-前一日": true,
            "举报监控5线-前一日": true,
            "举报监控6线-前一日": true,
            "举报监控7线-前一日": true,
            "举报监控8线-前一日": true,
            "举报监控1-预警": true,
            "举报监控2-预警": true,
            "举报监控3-预警": true,
            "举报监控4-预警": true,
            "举报监控5-预警": true,
            "举报监控6-预警": true,
            "举报监控7-预警": true,
            "举报监控8-预警": true
        },
        "data": [
            {
                "name": "举报监控1线"
            },
            {
                "name": "举报监控2线"
            },
            {
                "name": "举报监控3线"
            },
            {
                "name": "举报监控4线"
            },
            {
                "name": "举报监控5线"
            },
            {
                "name": "举报监控6线"
            },
            {
                "name": "举报监控7线"
            },
            {
                "name": "举报监控8线"
            }
        ]
    },
    "xAxis": [
        {
            "type": "time",
            "axisLabel": {
                "color": "#5F6063",
                "fontSize": 12
            },
            "axisTick": {
                "show": false
            },
            "axisLine": {
                "lineStyle": {
                    "color": "#C8C9CC"
                }
            }
        }
    ],
    "yAxis": [
        {
            "axisLabel": {
                "color": "#5F6063",
                "fontSize": 12
            },
            "splitLine": {
                "lineStyle": {
                    "type": "dashed"
                }
            },
            "type": "value"
        }
    ],
    "series": [
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控1线",
            "itemStyle": {
                "color": "#3491FA"
            },
            "data": [
                [
                    1646150400000,
                    43598
                ],
                [
                    1646154000000,
                    80655
                ],
                [
                    1646157600000,
                    42300
                ],
                [
                    1646161200000,
                    74783
                ],
                [
                    1646164800000,
                    48897
                ],
                [
                    1646168400000,
                    13850
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控2线",
            "itemStyle": {
                "color": "#14C9C9"
            },
            "data": [
                [
                    1646150400000,
                    53096
                ],
                [
                    1646154000000,
                    82320
                ],
                [
                    1646157600000,
                    13959
                ],
                [
                    1646161200000,
                    15822
                ],
                [
                    1646164800000,
                    29189
                ],
                [
                    1646168400000,
                    76236
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控3线",
            "itemStyle": {
                "color": "#00B42A"
            },
            "data": [
                [
                    1646150400000,
                    72094
                ],
                [
                    1646154000000,
                    86553
                ],
                [
                    1646157600000,
                    60285
                ],
                [
                    1646161200000,
                    49645
                ],
                [
                    1646164800000,
                    47203
                ],
                [
                    1646168400000,
                    27309
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控4线",
            "itemStyle": {
                "color": "#9FDB1D"
            },
            "data": [
                [
                    1646150400000,
                    34913
                ],
                [
                    1646154000000,
                    95583
                ],
                [
                    1646157600000,
                    6330
                ],
                [
                    1646161200000,
                    705
                ],
                [
                    1646164800000,
                    11534
                ],
                [
                    1646168400000,
                    19314
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控5线",
            "itemStyle": {
                "color": "#FADC19"
            },
            "data": [
                [
                    1646150400000,
                    60066
                ],
                [
                    1646154000000,
                    3784
                ],
                [
                    1646157600000,
                    87573
                ],
                [
                    1646161200000,
                    94298
                ],
                [
                    1646164800000,
                    48674
                ],
                [
                    1646168400000,
                    51378
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控6线",
            "itemStyle": {
                "color": "#FF7D00"
            },
            "data": [
                [
                    1646150400000,
                    32353
                ],
                [
                    1646154000000,
                    71825
                ],
                [
                    1646157600000,
                    60284
                ],
                [
                    1646161200000,
                    33771
                ],
                [
                    1646164800000,
                    96328
                ],
                [
                    1646168400000,
                    86376
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控7线",
            "itemStyle": {
                "color": "#F53F3F"
            },
            "data": [
                [
                    1646150400000,
                    56096
                ],
                [
                    1646154000000,
                    49415
                ],
                [
                    1646157600000,
                    17815
                ],
                [
                    1646161200000,
                    6051
                ],
                [
                    1646164800000,
                    39671
                ],
                [
                    1646168400000,
                    66010
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控8线",
            "itemStyle": {
                "color": "#722ED1"
            },
            "data": [
                [
                    1646150400000,
                    76293
                ],
                [
                    1646154000000,
                    27485
                ],
                [
                    1646157600000,
                    81845
                ],
                [
                    1646161200000,
                    7956
                ],
                [
                    1646164800000,
                    86984
                ],
                [
                    1646168400000,
                    17409
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "lineStyle": {
                "type": "dashed"
            },
            "name": "举报监控1线-前一日",
            "itemStyle": {
                "color": "#3491FA"
            },
            "data": [
                [
                    1646150400000,
                    82678
                ],
                [
                    1646154000000,
                    85872
                ],
                [
                    1646157600000,
                    78249
                ],
                [
                    1646161200000,
                    84027
                ],
                [
                    1646164800000,
                    88403
                ],
                [
                    1646168400000,
                    42504
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "lineStyle": {
                "type": "dashed"
            },
            "name": "举报监控2线-前一日",
            "itemStyle": {
                "color": "#14C9C9"
            },
            "data": [
                [
                    1646150400000,
                    80599
                ],
                [
                    1646154000000,
                    71581
                ],
                [
                    1646157600000,
                    23339
                ],
                [
                    1646161200000,
                    24612
                ],
                [
                    1646164800000,
                    74124
                ],
                [
                    1646168400000,
                    79979
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "lineStyle": {
                "type": "dashed"
            },
            "name": "举报监控3线-前一日",
            "itemStyle": {
                "color": "#00B42A"
            },
            "data": [
                [
                    1646150400000,
                    65508
                ],
                [
                    1646154000000,
                    71837
                ],
                [
                    1646157600000,
                    59574
                ],
                [
                    1646161200000,
                    18915
                ],
                [
                    1646164800000,
                    9332
                ],
                [
                    1646168400000,
                    92060
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "lineStyle": {
                "type": "dashed"
            },
            "name": "举报监控4线-前一日",
            "itemStyle": {
                "color": "#9FDB1D"
            },
            "data": [
                [
                    1646150400000,
                    82256
                ],
                [
                    1646154000000,
                    92162
                ],
                [
                    1646157600000,
                    1160
                ],
                [
                    1646161200000,
                    61541
                ],
                [
                    1646164800000,
                    63299
                ],
                [
                    1646168400000,
                    8568
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "lineStyle": {
                "type": "dashed"
            },
            "name": "举报监控5线-前一日",
            "itemStyle": {
                "color": "#FADC19"
            },
            "data": [
                [
                    1646150400000,
                    6287
                ],
                [
                    1646154000000,
                    42557
                ],
                [
                    1646157600000,
                    61508
                ],
                [
                    1646161200000,
                    20122
                ],
                [
                    1646164800000,
                    32276
                ],
                [
                    1646168400000,
                    88950
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "lineStyle": {
                "type": "dashed"
            },
            "name": "举报监控6线-前一日",
            "itemStyle": {
                "color": "#FF7D00"
            },
            "data": [
                [
                    1646150400000,
                    850
                ],
                [
                    1646154000000,
                    30781
                ],
                [
                    1646157600000,
                    7618
                ],
                [
                    1646161200000,
                    48103
                ],
                [
                    1646164800000,
                    60910
                ],
                [
                    1646168400000,
                    78382
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "lineStyle": {
                "type": "dashed"
            },
            "name": "举报监控7线-前一日",
            "itemStyle": {
                "color": "#F53F3F"
            },
            "data": [
                [
                    1646150400000,
                    64969
                ],
                [
                    1646154000000,
                    80990
                ],
                [
                    1646157600000,
                    2154
                ],
                [
                    1646161200000,
                    46017
                ],
                [
                    1646164800000,
                    79549
                ],
                [
                    1646168400000,
                    87259
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "lineStyle": {
                "type": "dashed"
            },
            "name": "举报监控8线-前一日",
            "itemStyle": {
                "color": "#722ED1"
            },
            "data": [
                [
                    1646150400000,
                    29568
                ],
                [
                    1646154000000,
                    69111
                ],
                [
                    1646157600000,
                    42090
                ],
                [
                    1646161200000,
                    41043
                ],
                [
                    1646164800000,
                    51447
                ],
                [
                    1646168400000,
                    26474
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控1-预警",
            "itemStyle": {
                "color": "#FF0000"
            },
            "data": [
                [
                    1646150400000,
                    14549
                ],
                [
                    1646154000000,
                    32377
                ],
                [
                    1646157600000,
                    31587
                ],
                [
                    1646161200000,
                    98009
                ],
                [
                    1646164800000,
                    75883
                ],
                [
                    1646168400000,
                    23586
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控2-预警",
            "itemStyle": {
                "color": "#FF0000"
            },
            "data": [
                [
                    1646150400000,
                    61074
                ],
                [
                    1646154000000,
                    84901
                ],
                [
                    1646157600000,
                    76919
                ],
                [
                    1646161200000,
                    11275
                ],
                [
                    1646164800000,
                    95853
                ],
                [
                    1646168400000,
                    13427
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控3-预警",
            "itemStyle": {
                "color": "#FF0000"
            },
            "data": [
                [
                    1646150400000,
                    32882
                ],
                [
                    1646154000000,
                    78418
                ],
                [
                    1646157600000,
                    61274
                ],
                [
                    1646161200000,
                    19552
                ],
                [
                    1646164800000,
                    31794
                ],
                [
                    1646168400000,
                    42736
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控4-预警",
            "itemStyle": {
                "color": "#FF0000"
            },
            "data": [
                [
                    1646150400000,
                    70919
                ],
                [
                    1646154000000,
                    7570
                ],
                [
                    1646157600000,
                    29931
                ],
                [
                    1646161200000,
                    36557
                ],
                [
                    1646164800000,
                    3302
                ],
                [
                    1646168400000,
                    68369
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控5-预警",
            "itemStyle": {
                "color": "#FF0000"
            },
            "data": [
                [
                    1646150400000,
                    28921
                ],
                [
                    1646154000000,
                    76956
                ],
                [
                    1646157600000,
                    33867
                ],
                [
                    1646161200000,
                    82283
                ],
                [
                    1646164800000,
                    17142
                ],
                [
                    1646168400000,
                    83946
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控6-预警",
            "itemStyle": {
                "color": "#FF0000"
            },
            "data": [
                [
                    1646150400000,
                    11196
                ],
                [
                    1646154000000,
                    85477
                ],
                [
                    1646157600000,
                    16724
                ],
                [
                    1646161200000,
                    32621
                ],
                [
                    1646164800000,
                    8354
                ],
                [
                    1646168400000,
                    96175
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控7-预警",
            "itemStyle": {
                "color": "#FF0000"
            },
            "data": [
                [
                    1646150400000,
                    47161
                ],
                [
                    1646154000000,
                    74459
                ],
                [
                    1646157600000,
                    27815
                ],
                [
                    1646161200000,
                    30169
                ],
                [
                    1646164800000,
                    72703
                ],
                [
                    1646168400000,
                    14523
                ]
            ]
        },
        {
            "xAxisIndex": 0,
            "yAxisIndex": 0,
            "type": "line",
            "smooth": true,
            "showSymbol": false,
            "name": "举报监控8-预警",
            "itemStyle": {
                "color": "#FF0000"
            },
            "data": [
                [
                    1646150400000,
                    16950
                ],
                [
                    1646154000000,
                    75731
                ],
                [
                    1646157600000,
                    54834
                ],
                [
                    1646161200000,
                    64849
                ],
                [
                    1646164800000,
                    83022
                ],
                [
                    1646168400000,
                    13854
                ]
            ]
        }
    ]
}
```

**Comment by plainheart** [comment]
I ran your demo but found no errors.
