### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'states') in pie/labelLayout.js when minShowLabelAngle removes a small angle and label position is "inside"

### ISSUE THREAD

**Issue by piwatkins** [apache/echarts#18146]
### Version

3.53.1

### Steps to Reproduce

I'm unable to recreate the error in JSFiddle.

This happens when I have a pie chart with label: {position: "inside"} and minShowLabelAngle is set low enough that an small-angle item gets left out.

### Current Behavior

Error stack:

labelLayout.js:357 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'states')
    at SeriesData.<anonymous> (labelLayout.js:357:22)
    at DataStore.each (DataStore.js:1009:11)
    at SeriesData.each (SeriesData.js:756:17)
    at pieLabelLayout (labelLayout.js:336:8)
    at PieView.render (PieView.js:291:5)
    at Task.progress (Chart.js:233:20)
    at Task._doProgress (task.js:187:10)
    at Task.perform (task.js:153:16)
    at echarts.js:1825:24
    at GlobalModel.<anonymous> (Global.js:654:10)

pie/labelLayout.js is getting labelLine:

var labelLine = sector.getTextGuideLine();

and that's returning undefined, then it's trying to read from it:

   if (Math.abs(sectorShape.endAngle - sectorShape.startAngle) < minShowLabelRadian) {
      each(label.states, setNotShow);
      each(labelLine.states, setNotShow);  // THIS ERRORS
      label.ignore = labelLine.ignore = true;
      return;
    }

### Expected Behavior

No javascript errors

### Environment

```markdown
- OS: Windows 10
- Browser: Edge 108.0.1462.54
- Framework: Svelte 3.53.1, Echarts 5.40
```

**Comment by plainheart** [comment]
5.4.1 has fixed this bug.
