### ISSUE TITLE
[Bug] line chart can't display when visualmap pieces with single set(one limit line)

### ISSUE THREAD

**Issue by koallamara** [apache/echarts#18274]
### Version

5.1.2

### Link to Minimal Reproduction

[Demo](https://echarts.apache.org/examples/en/editor.html?c=line-aqi&code=CQOg5gpgLgFASgeQQFQPoAUCCyASACAajwHIB6AEwEMpLTKBne6C62ygRwEsBaAIwk4ArTgDswIQfQD2I4gBo8AMwCuIgMZROMvDCo0AlHgDeAKDx4AtgE8AwgAtKAJyggmUBAAdNMmGfM6pLy0RPABeYz9_PE0oABsIAC4IqKioCAAPKCTiACEBYTE8TABFAEl5SJT4xSySAEYAUmJK8wBfORa8dMx0znok0xT_PUokkZALSg8YFXVvEJhONItDQaH_R2hlRxCliAsAbQAGAF0Abk62_U72zqsevoHboYA3PuVKWIBZKYHL6MCSQArEcOus8I5OGA7LU6qD_h5OBA1BB-ngDv9zGtweZYrUAMxHeE4_xqKSxKSObIAYgAnPibABRI4AdmaJOeOOxOLABKJYJJeDJFKpJGpmBs-JyACZMOyca1_icbgKokxIai_uCRJQLIkSHkhKIwEUyhVwVArB59cRYqIIOb1iMxqwJlMZqoNMEdHsVskcZsoNtdssDnVzv9WvpVSlJo4ANYAGXtWpxzvR3PB916aMJR0xeFayvBiqGpf8Ub8-guUbOQA)

### Steps to Reproduce

(It's related with #11847) 
1. I want to show line chart with **one limit line** (ex: yAxis: 300, theres no range data-like max/min-, just one)
2. using `markLine` and `visualMap-pieces` to present limit 
3. I can't check line chart

```
echarts.min.js:45 Uncaught TypeError: Cannot read properties of undefined (reading 'coord')
    at SS (echarts.min.js:45:339092)
    at e.render (echarts.min.js:45:341657)
    at t.progress (echarts.min.js:45:166846)
    at t._doProgress (echarts.min.js:45:135365)
    at t.perform (echarts.min.js:45:134937)
    at echarts.min.js:45:216009
    at e.<anonymous> (echarts.min.js:45:116240)
    at Array.forEach (<anonymous>)
    at E (echarts.min.js:35:5064)
    at e.eachSeries (echarts.min.js:45:116160)
```

### Current Behavior

line chart can't present

![image](https://user-images.githubusercontent.com/25011305/218935289-1e450a07-5b06-464d-ae91-b0e25171728b.png)

### Expected Behavior

It should display like a scatter chart.

![image](https://user-images.githubusercontent.com/25011305/218935360-5d9dd158-8afa-4c26-8b01-821cddbcc9ec.png)

### Environment

```markdown
- OS: window 10
- Browser: chrome
- Framework: vue.js 2.6.14
```

**Comment by helgasoft** [comment]
duplicate of #18268 and others

**Comment by jlefeaux** [comment]
Can confirm.  I circumvented the issue by adding a 2nd, "artificial" piece with the same color.

```
pieces: [
        {
          lte: 180,
          color: "#292929",
        },
        {
          gt: 180,
          lte: 184,
          color: "#292929",
        },
        {
          gt: 184,
          color: "#e03131",
        },
      ],
```

**Comment by helgasoft** [comment]
@jlefeaux, the trick with a middle piece works, but it displays an extra entry in the legend.
There is **another workaround** - to subtract a small value from the first piece: ```lt:300-0.001```. 
Then the legend keeps only original values - [Demo](https://echarts.apache.org/examples/en/editor.html?code=CQOg5gpgLgFASgeQQFQPoAUCCyASACAajwHIB6AEwEMpLTKBne6C62ygRwEsBaAIwk4ArTgDswIQfQD2I4gBo8AMwCuIgMZROMvDCo0AlHgDeAKDx4AtgE8AwgAtKAJyggmUBAAdNMmGfM6pLy0RPABeYz9_PE0oABsIAC4IqKioCAAPKCTiACEBYTE8TABFAEl5SJT4xSySAEYAUmJK8wBfORa8dMx0znok0xT_PUokkZALSg8YFXVvEJhONItDQaH_R2hlRxCliAsAbQAGAF0Abk62_U72zqsevoHboYA3PuVKWIBZKYHL6MCSQArEcOus8I5OGA7LU6qD_h5OBA1BB-ngDv9zGtweZYrUAMxHI7cI4gIl1ME48xqKSxKSObIAYgAnPibABRI4AdmaVOeOKMeEx_jABKJlKpNLpDJIjMwNnxOQATJheTjWv8TjcJf4mJDUX9wSJKBZEiQ8kJRGAimUKuCoFYPGbiPQ1NQ0o47esRmNWBMpjNVBpgjo9itkjjNlBtrtlgc6ud_q19DqopNHABrAAyojN2O9rCSB0F916aMJRzwrS14I1Qzr_mTfn0F2TZyAA).
![line-aqi](https://github.com/apache/echarts/assets/13038071/29ac7e2c-f817-4368-9cc7-e16f167f1fcf)
