### ISSUE TITLE
[Bug] series endLabel failed if no point on chart

### ISSUE THREAD

**Issue by francois-achache** [apache/echarts#18746]
### Version

5.4.1

### Link to Minimal Reproduction

https://codesandbox.io/s/cdy362?file=/index.js

### Steps to Reproduce

Create echart without option
option = {
  xAxis: {
    type: 'time',
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [
        [new Date('1973-11-25:00:00'), null], 
        [new Date('1973-11-25:01:00'), null], 
        [new Date('1973-11-25:02:00'), null], 
        [new Date('1973-11-25:03:00'), null], 
        [new Date('1973-11-25:04:00'), null],
        [new Date('1973-11-25:05:00'), null], 
        [new Date('1973-11-25:06:00'), 5]],
      type: 'line',
      endLabel: {show: true}
    }
  ]
};
Works...
option = {
  xAxis: {
    type: 'time',
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [
        [new Date('1973-11-25:00:00'), null], 
        [new Date('1973-11-25:01:00'), null], 
        [new Date('1973-11-25:02:00'), null], 
        [new Date('1973-11-25:03:00'), null], 
        [new Date('1973-11-25:04:00'), null],
        [new Date('1973-11-25:05:00'), null], 
        [new Date('1973-11-25:06:00'), null]],
      type: 'line',
      endLabel: {show: true}
    }
  ]
};
Fail...
failed to run code TypeError: uc(...).setLabelText is not a function
    at e._endLabelOnDuring (echarts.min.js:45:347602)
    at RS.l (echarts.min.js:45:339639)
    at RS (echarts.min.js:45:339942)
    at e.render (echarts.min.js:45:342029)
    at t.progress (echarts.min.js:45:166701)
    at t._doProgress (echarts.min.js:45:135208)
    at t.perform (echarts.min.js:45:134780)
    at echarts.min.js:45:215513
    at e.<anonymous> (echarts.min.js:45:116265)
    at Array.forEach (<anonymous>)

### Current Behavior

if no only value === null in area/chart
failed to run code TypeError: uc(...).setLabelText is not a function
    at e._endLabelOnDuring (echarts.min.js:45:347602)
    at RS.l (echarts.min.js:45:339639)
    at RS (echarts.min.js:45:339942)
    at e.render (echarts.min.js:45:342029)
    at t.progress (echarts.min.js:45:166701)
    at t._doProgress (echarts.min.js:45:135208)
    at t.perform (echarts.min.js:45:134780)
    at echarts.min.js:45:215513
    at e.<anonymous> (echarts.min.js:45:116265)
    at Array.forEach (<anonymous>)

### Expected Behavior

no error

### Environment

```markdown
- OS: Windows 11
- Browser: Edge
- Framework: angular
```

**Comment by helgasoft** [comment]
maybe it will work with some decent dates...

**Comment by francois-achache** [comment]
no, just change the last value 5 or null and that's work or not
No choice I have to disabled this feature in my graph

**Comment by helgasoft** [comment]
[endLabel](https://echarts.apache.org/en/option.html#series-line.endLabel) displays the last value. If all values are _null_, then there is no label.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWAPAgliAzgFzKxgCeIApiQOSQC2VtsAvgDTqbl6ElIcusAlQBOEKsVgBtIZlQZMSgCYBDMKpKzFSpdOhUA7rAAi6qgApaARgCcAdgDMAWmvXnAJgCsRAAwe_X1oASnZYaABXABsogF0wuV0ZA2MzMEsbBxc3Tx9fR0CQsMiY-NhE3X0jU3MrOydXd28_ABZC0NhHeIq9FJr0uqzG3L88oI6SuISdJKrU2syGnObfADZ24ui4nu6ZzApqOiiIA1owgnIGACNgKIBlCAAvGmsvTj3YKmhlABlVK6oUX4BAAFsBDCQwKIIlRBDNWEJYuhWABuIA)

**Comment by francois-achache** [comment]
yes  for sure, but doesnt have to raise an error in jsconsole
