### ISSUE TITLE
[Bug] renderToSVG does not work with Node.js 21.5.0

### ISSUE THREAD

**Issue by andreasloe** [apache/echarts#19670]
### Version

5.5.0

### Link to Minimal Reproduction

```markdown
const echarts = require('echarts');  
var m = echarts.init(null, null); 
var o={ "series":[{"data":[["1:49"],["2:53"]]}] }; 
m.setOption(o);
const svg = m.renderToSVGString();
```

### Steps to Reproduce

No user interaction, just running the code gives the following message
```markdown
/home/pi/node_modules/echarts/dist/echarts.js:123
        env.touchEventsSupported = 'ontouchstart' in window && !browser.ie && !browser.edge;
                                                     ^

ReferenceError: window is not defined
    at detect (/home/pi/node_modules/echarts/dist/echarts.js:123:54)
    at /home/pi/node_modules/echarts/dist/echarts.js:97:9
    at /home/pi/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/pi/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)

Node.js v21.5.0
```

### Current Behavior

I get an error message

### Expected Behavior

I expect an SVG string.

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye), Linux 6.1.21-v8+ aarch64
- Browser: none
- Framework: none
```

**Comment by plainheart** [comment]
Can you run the following commands and paste the result here?

```js
const echarts = require('echarts');  
console.log(echarts.env);
console.log(navigator.userAgent);
```

**Comment by andreasloe** [comment]
Thank you very much for your help, plainheart! 

I am running eCharts on a raspberry pi using NodeJS with the following code (this is the contents of the file bild.js)
```
const echarts = require('echarts');  
console.log(echarts.env);
console.log(navigator.userAgent);
```
and get 
```
node bild.js
/home/pi/node_modules/echarts/dist/echarts.js:123
        env.touchEventsSupported = 'ontouchstart' in window && !browser.ie && !browser.edge;
                                                     ^

ReferenceError: window is not defined
    at detect (/home/pi/node_modules/echarts/dist/echarts.js:123:54)
    at /home/pi/node_modules/echarts/dist/echarts.js:97:9
    at /home/pi/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/pi/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)

Node.js v21.5.0```
 
I suspect since no "real" browser is involved there is no window to be found.

**Comment by andreasloe** [comment]
PS If I add "const puppeteer = require('puppeteer');" to the code the result is _exactly_ the same.

**Comment by plainheart** [comment]
Can you just simply run the command?
```js
console.log(navigator.userAgent);
```

**Comment by andreasloe** [comment]
```
i@raspfhem:~ $ node
Welcome to Node.js v21.5.0
> console.log(navigator.userAgent);
Node.js/21
undefined
> 
```

**Comment by plainheart** [comment]
I'm not sure why it enters the `detect` branch. I tested the same Node.js version in Windows and it entered the `In node` branch. You can try to debug it if possible.

**Comment by andreasloe** [comment]
Is this in any way helpful?
```
node -p "require('util').inspect(process.config)"
{
  target_defaults: {
    cflags: [ '-msign-return-address=all' ],
    default_configuration: 'Release',
    defines: [
      'NODE_OPENSSL_CONF_NAME=nodejs_conf',
      'NODE_OPENSSL_HAS_QUIC',
      'ICU_NO_USER_DATA_OVERRIDE'
    ],
    include_dirs: [],
    libraries: []
  },
  variables: {
    arm_fpu: 'neon',
    asan: 0,
    coverage: false,
    dcheck_always_on: 0,
    debug_nghttp2: false,
    debug_node: false,
    enable_lto: false,
    enable_pgo_generate: false,
    enable_pgo_use: false,
    error_on_warn: false,
    force_dynamic_crt: 0,
    gas_version: '2.35',
    host_arch: 'arm64',
    icu_data_in: '../../deps/icu-tmp/icudt74l.dat',
    icu_endianness: 'l',
    icu_gyp_path: 'tools/icu/icu-generic.gyp',
    icu_path: 'deps/icu-small',
    icu_small: false,
    icu_ver_major: '74',
    is_debug: 0,
    libdir: 'lib',
    llvm_version: '0.0',
    napi_build_version: '9',
    node_builtin_shareable_builtins: [
      'deps/cjs-module-lexer/lexer.js',
      'deps/cjs-module-lexer/dist/lexer.js',
      'deps/undici/undici.js'
    ],
    node_byteorder: 'little',
    node_debug_lib: false,
    node_enable_d8: false,
    node_enable_v8_vtunejit: false,
    node_fipsinstall: false,
    node_install_corepack: true,
    node_install_npm: true,
    node_library_files: [
      'lib/_http_agent.js',
      'lib/_http_client.js',
      'lib/_http_common.js',
      'lib/_http_incoming.js',
      'lib/_http_outgoing.js',
      'lib/_http_server.js',
      'lib/_stream_duplex.js',
      'lib/_stream_passthrough.js',
      'lib/_stream_readable.js',
      'lib/_stream_transform.js',
      'lib/_stream_wrap.js',
      'lib/_stream_writable.js',
      'lib/_tls_common.js',
      'lib/_tls_wrap.js',
      'lib/assert.js',
      'lib/assert/strict.js',
      'lib/async_hooks.js',
      'lib/buffer.js',
      'lib/child_process.js',
      'lib/cluster.js',
      'lib/console.js',
      'lib/constants.js',
      'lib/crypto.js',
      'lib/dgram.js',
      'lib/diagnostics_channel.js',
      'lib/dns.js',
      'lib/dns/promises.js',
      'lib/domain.js',
      'lib/events.js',
      'lib/fs.js',
      'lib/fs/promises.js',
      'lib/http.js',
      'lib/http2.js',
      'lib/https.js',
      'lib/inspector.js',
      'lib/inspector/promises.js',
      'lib/internal/abort_controller.js',
      'lib/internal/assert.js',
      'lib/internal/assert/assertion_error.js',
      'lib/internal/assert/calltracker.js',
      'lib/internal/async_hooks.js',
      'lib/internal/blob.js',
      'lib/internal/blocklist.js',
      'lib/internal/bootstrap/node.js',
      'lib/internal/bootstrap/realm.js',
      'lib/internal/bootstrap/shadow_realm.js',
      'lib/internal/bootstrap/switches/does_not_own_process_state.js',
      'lib/internal/bootstrap/switches/does_own_process_state.js',
      'lib/internal/bootstrap/switches/is_main_thread.js',
      'lib/internal/bootstrap/switches/is_not_main_thread.js',
      'lib/internal/bootstrap/web/exposed-wildcard.js',
      'lib/internal/bootstrap/web/exposed-window-or-worker.js',
      'lib/internal/buffer.js',
      'lib/internal/child_process.js',
      'lib/internal/child_process/serialization.js',
      'lib/internal/cli_table.js',
      'lib/internal/cluster/child.js',
      'lib/internal/cluster/primary.js',
      'lib/internal/cluster/round_robin_handle.js',
      'lib/internal/cluster/shared_handle.js',
      'lib/internal/cluster/utils.js',
      'lib/internal/cluster/worker.js',
      'lib/internal/console/constructor.js',
      'lib/internal/console/global.js',
      'lib/internal/constants.js',
      'lib/internal/crypto/aes.js',
      'lib/internal/crypto/certificate.js',
      'lib/internal/crypto/cfrg.js',
      'lib/internal/crypto/cipher.js',
      'lib/internal/crypto/diffiehellman.js',
      'lib/internal/crypto/ec.js',
      'lib/internal/crypto/hash.js',
      'lib/internal/crypto/hashnames.js',
      'lib/internal/crypto/hkdf.js',
      'lib/internal/crypto/keygen.js',
      'lib/internal/crypto/keys.js',
      'lib/internal/crypto/mac.js',
      'lib/internal/crypto/pbkdf2.js',
      'lib/internal/crypto/random.js',
      'lib/internal/crypto/rsa.js',
      'lib/internal/crypto/scrypt.js',
      'lib/internal/crypto/sig.js',
      'lib/internal/crypto/util.js',
      'lib/internal/crypto/webcrypto.js',
      'lib/internal/crypto/webidl.js',
      'lib/internal/crypto/x509.js',
      'lib/internal/debugger/inspect.js',
      'lib/internal/debugger/inspect_client.js',
      'lib/internal/debugger/inspect_repl.js',
      'lib/internal/dgram.js',
      'lib/internal/dns/callback_resolver.js',
      'lib/internal/dns/promises.js',
      'lib/internal/dns/utils.js',
      'lib/internal/encoding.js',
      'lib/internal/error_serdes.js',
      'lib/internal/errors.js',
      'lib/internal/event_target.js',
      'lib/internal/events/symbols.js',
      'lib/internal/file.js',
      'lib/internal/fixed_queue.js',
      ... 214 more items
    ],
    node_module_version: 120,
    node_no_browser_globals: false,
    node_prefix: '/',
    node_release_urlbase: 'https://nodejs.org/download/release/',
    node_section_ordering_info: '',
    node_shared: false,
    node_shared_brotli: false,
    node_shared_cares: false,
    node_shared_http_parser: false,
    node_shared_libuv: false,
    node_shared_nghttp2: false,
    node_shared_nghttp3: false,
    node_shared_ngtcp2: false,
    node_shared_openssl: false,
    node_shared_zlib: false,
    node_tag: '',
    node_target_type: 'executable',
    node_use_bundled_v8: true,
    node_use_node_code_cache: true,
    node_use_node_snapshot: true,
    node_use_openssl: true,
    node_use_v8_platform: true,
    node_with_ltcg: false,
    node_without_node_options: false,
    node_write_snapshot_as_array_literals: false,
    openssl_is_fips: false,
    openssl_quic: true,
    ossfuzz: false,
    shlib_suffix: 'so.120',
    single_executable_application: true,
    target_arch: 'arm64',
    v8_enable_31bit_smis_on_64bit_arch: 0,
    v8_enable_extensible_ro_snapshot: 0,
    v8_enable_gdbjit: 0,
    v8_enable_hugepage: 0,
    v8_enable_i18n_support: 1,
    v8_enable_inspector: 1,
    v8_enable_javascript_promise_hooks: 1,
    v8_enable_lite_mode: 0,
    v8_enable_maglev: 0,
    v8_enable_object_print: 1,
    v8_enable_pointer_compression: 0,
    v8_enable_shared_ro_heap: 1,
    v8_enable_v8_checks: 0,
    v8_enable_webassembly: 1,
    v8_no_strict_aliasing: 1,
    v8_optimized_debug: 1,
    v8_promise_internal_field_count: 1,
    v8_random_seed: 0,
    v8_trace_maps: 0,
    v8_use_siphash: 1,
    want_separate_host_toolset: 0
  }
}
```

**Comment by plainheart** [comment]
Try to run this code block and see the output.

```js
if (typeof document === 'undefined' && typeof self !== 'undefined') {
    console.log('entered InWorker branch')
}
else if (
    typeof navigator === 'undefined'
    || navigator.userAgent.indexOf('Node.js') === 0
) {
    console.log('entered InNode branch', navigator)
}
else {
    console.log('entered detect branch')
}
```

**Comment by andreasloe** [comment]
`entered InNode branch Navigator {}`
`undefined`

**Comment by andreasloe** [comment]
` if ( typeof navigator === 'undefined'  ) { console.log('navigator undefined') }`
`undefined`

**Comment by andreasloe** [comment]
and also
` if ( navigator.userAgent.indexOf('Node.js') === 0 ) { console.log('index=0') }`
`index=0`
`undefined`

**Comment by plainheart** [comment]
Looks weird. If it entered the InNode branch, I think the error should not be thrown.

![image](https://github.com/apache/echarts/assets/26999792/ca18fa5e-d8c8-4446-837e-3cfeb656d990)

**Comment by andreasloe** [comment]
I changed **N**ode.js into **n**ode.js and got

```if (typeof document === 'undefined' && typeof self !== 'undefined') {
    console.log('entered InWorker branch')
}
else if (
    typeof navigator === 'undefined'
    || navigator.userAgent.indexOf('Node.js') === 0
) {
    console.log('entered InNode branch', navigator)
}
else {
    console.log('entered detect branch')
}
entered detect branch
undefined```

**Comment by plainheart** [comment]
> I changed Node.js into node.js and got

Current `Node.js` is right. You don't need to change it.

**Comment by andreasloe** [comment]
I just removed node.js, update/upgrade and installed it again - to no avail.

**Comment by andreasloe** [comment]
What else can I do to find out what is going on here?

**Comment by plainheart** [comment]
I'm afraid I can't reproduce your issue. I ran the following code with Node.js 21.5.0 (node-v21.5.0-win-x64) in Windows, it can output the SVG string as expected.

```js
console.log('Node.js userAgent:', navigator.userAgent);

const echarts = require('echarts');
console.log('ECharts env:', echarts.env, 'In Node:', echarts.env.node);
const chart = echarts.init(null, null, {
  renderer: 'svg',
  ssr: true,
  width: 800,
  height: 600
});
const option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line'
    }
  ]
};
chart.setOption(option);
const svgStr = chart.renderToSVGString();
console.log('svgStr:\n', svgStr);

// write to svg file
require('node:fs').writeFileSync('./output.svg', svgStr);

chart.dispose();
```

**Comment by andreasloe** [comment]
Then it is a Mac issue? I am using a M1 with Mac OS 14.3.1 (23D60) with exactly the same code as above, ,still an error.

Puh. I have no idea.

**Comment by andreasloe** [comment]
Either it is a Linux issue (I am using a raspberry) or my installation is cracked. 

I will try to install nodejs on another RPi to test that.

**Comment by andreasloe** [comment]
I justed checked it with another RPi and there everything worked. So it has to do with my installation. I am closing the bug - nevertheless, thank you for your effort and time you spent on my issue!

**Comment by andreasloe** [comment]
In case someone is having the same error: I now suspect that I installed the wrong version of node or mixed something up there. I recommend https://www.instructables.com/Install-Nodejs-and-Npm-on-Raspberry-Pi/ in case you have a raspberry.
