### ISSUE TITLE
[Bug] Vue3项目中引入echarts会有isFunction is not a function问题

### ISSUE THREAD

**Issue by ykvou** [apache/echarts#19745]
### Version

5.4.3

### Link to Minimal Reproduction

none

### Steps to Reproduce

本项目使用的技术栈是vue+ts+vite. vue的版本是3.3.4，当在该项目中安装echarts之后并在组件中引入使用，运行项目后，控制台报出以下错误信息：
```
Uncaught TypeError: isFunction is not a function
    at defineComponent (runtime-core.esm-bundler.js:2252:10)
    at index.js:6:16
```
是否是版本不兼容的问题？请问什么版本可以正常使用？

### Current Behavior

1. 一旦在项目中安装echarts就会有`isFunction is not a function`的问题，卸载echarts之后该问题解除，项目正常运行
2. 在使用vue-smooth-dnd这个第三方库时也遇到同样的问题，替换为vue3-smooth-dnd之后问题解决，是否是echarts不兼容vue@3，有没有vue@3用户分享一下目前能正常使用，不影响项目运行的echarts版本

### Expected Behavior

1. 希望能解决echarts在vue3无法正常使用的问题

### Environment

```markdown
- OS:windows11
- Browser:Chrome 122.0.6261.129
- Framework:Vue@3.3.4
```

**Comment by ykvou** [comment]
问题已解决。是配置的自动格式化把ant-design-vue的引入排在vue的引入前面导致的，更换一下vue与antdv的引入顺序就解决了
