### ISSUE TITLE
bug: Please provide an example of using dimensions  in series 

### ISSUE THREAD

**Issue by sunili** [apache/echarts#6421]
### One-line summary [问题简述]:
Bar is not displayed by using following option object and following error observed on console,

echarts.min.js:24 Uncaught TypeError: Cannot read property 'width' of undefined
echarts.min.js:24 Uncaught TypeError: Cannot read property 'width' of undefined
echarts.min.js:24 Uncaught TypeError: Cannot read property 'width' of undefined
echarts.min.js:24 Uncaught TypeError: Cannot read property 'width' of undefined
echarts.min.js:24 Uncaught TypeError: Cannot read property 'width' of undefined
echarts.min.js:24 Uncaught TypeError: Cannot read property 'width' of undefined
    at r (http://gallerybox.echartsjs.com/dep/echarts/latest/echarts.min.js:24:12307)
    at Object.cartesian2d (http://gallerybox.echartsjs.com/dep/echarts/latest/echarts.min.js:24:14053)
    at n._add (http://gallerybox.echartsjs.com/dep/echarts/latest/echarts.min.js:24:12919)
    at n.execute (http://gallerybox.echartsjs.com/dep/echarts/latest/echarts.min.js:13:15842)
    at i._render (http://gallerybox.echartsjs.com/dep/echarts/latest/echarts.min.js:24:13382)
    at i.render (http://gallerybox.echartsjs.com/dep/echarts/latest/echarts.min.js:24:12573)
    at a.<anonymous> (http://gallerybox.echartsjs.com/dep/echarts/latest/echarts.min.js:1:8657)
    at i.<anonymous> (http://gallerybox.echartsjs.com/dep/echarts/latest/echarts.min.js:26:4259)
    at Array.forEach (native)
    at f (http://gallerybox.echartsjs.com/dep/echarts/latest/echarts.min.js:1:2106)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.3
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: 'Awesome Chart'
    },
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        },
    },
    xAxis: {
        data: ['Sun', 'Mon','tue']
    },
    yAxis: {
        type:'value'
    },
    series: [{
        type: 'bar',
        lineStyle : {
        
        },
       dimensions: ['dim1','dim2','dim3'],
        encode : {
          x :[0,2],
          y :[1],
          tooltip : [0,1,2],
        },
        data:[['Sun',220,'harry'], ['Mon',182,'james'],['tue',182,'tom']]
    }]
};

```

**Comment by alexptbg** [comment]
+1
